name: binance_app_ui
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  get: ^4.6.6
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  intl: ^0.19.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pngs/app-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
        - asset: assets/fonts/Satoshi-Light.otf
        - asset: assets/fonts/Satoshi-Medium.otf
        - asset: assets/fonts/Satoshi-Regular.otf
